services:

  api-gateway:
    ports:
      - "8085:8085"
    networks:
      - ecole

  ecole-portal:
    build:
      context: ./ecole-portal
      dockerfile: Dockerfile
      target: dev
    image: barssim/ecole-portal:develop
    ports:
      - "8080:8080"
    volumes:
      - ./ecole-portal:/app
      - /app/node_modules
    networks:
      - ecole
    environment:
      - REACT_APP_API_GATEWAY_URL=http://localhost:8085
      - REACT_APP_DEBUG=true

networks:
  ecole:
    external: true
