services:

  mysql-user:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: userDB
    networks:
      - ecole

  mysql-fin:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: finDB
    networks:
      - ecole

  usermanagement:
    image: barssim/usermanagement:latest
    depends_on:
      - mysql-user
    networks:
      - ecole

  finance-manager:
    image: barssim/finance-manager:latest
    depends_on:
      - mysql-fin
    networks:
      - ecole

  eureka-server:
    image: barssim/eureka-server:latest
    networks:
      - ecole

  api-gateway:
    image: barssim/solide-api-gateway:latest
      - usermanagement
      - finance-manager
    networks:
      - ecole

networks:
  ecole: