-- Insert tenant master data
INSERT IGNORE INTO tb_tenant (tenant_id, tenant_name, tenant_email) VALUES
('gardinia', 'Gardinia', 'noreply_gardinia@example.com'),
('qods', 'Qods', 'noreply_qods@example.com'),
('amana', 'Amana', 'noreply_amana@example.com');

-- Insert test users with roles
INSERT IGNORE INTO tb_user (userno, surname, firstname, email, adresse, password, role, tenant_id) VALUES
(1, 'admin', 'Gardinia', 'admin@school.com', 'Admin Street', 'Youssef83#', 'manager', 'gardinia'),
(2, 'parent', 'Parent', 'parent@school.com', 'Parent Street', 'parentpass', 'parent', 'gardinia'),
(3, 'student', 'Student', 'student@school.com', 'Student Street', 'studentpass', 'student', 'gardinia'),
(4, 'admin', 'Qods', 'manager@school.com', 'Manager Street', 'Halima68#', 'manager', 'qods'),
(5, 'teacher', 'Teacher', 'teacher@school.com', 'Teacher Street', 'teacherpass', 'teacher', 'qods'),
(6, 'finance', 'Finance', 'finance@school.com', 'Finance Street', 'financepass', 'finance', 'qods');

-- 30 teacher accounts (tenant 'gardinia'), 3 teachers per subject across 10 subjects.
-- Subject assignment is tracked in teacher-service.data.sql (tb table teacher_courses)
-- via the matching teacher_id (teacher-201 .. teacher-230).
INSERT IGNORE INTO tb_user (userno, surname, firstname, email, adresse, password, role, tenant_id) VALUES
(201, 'Alami', 'Karim', 'karim.alami@school.com', 'Enseignant - Mathématiques', 'teacherpass', 'teacher', 'gardinia'),
(202, 'Benjelloun', 'Salma', 'salma.benjelloun@school.com', 'Enseignante - Mathématiques', 'teacherpass', 'teacher', 'gardinia'),
(203, 'Ouazzani', 'Yassine', 'yassine.ouazzani@school.com', 'Enseignant - Mathématiques', 'teacherpass', 'teacher', 'gardinia'),
(204, 'Ziani', 'Nadia', 'nadia.ziani@school.com', 'Enseignante - Français', 'teacherpass', 'teacher', 'gardinia'),
(205, 'Belhaj', 'Omar', 'omar.belhaj@school.com', 'Enseignant - Français', 'teacherpass', 'teacher', 'gardinia'),
(206, 'Cherkaoui', 'Imane', 'imane.cherkaoui@school.com', 'Enseignante - Français', 'teacherpass', 'teacher', 'gardinia'),
(207, 'Filali', 'Rachid', 'rachid.filali@school.com', 'Enseignant - Arabe', 'teacherpass', 'teacher', 'gardinia'),
(208, 'Guessous', 'Latifa', 'latifa.guessous@school.com', 'Enseignante - Arabe', 'teacherpass', 'teacher', 'gardinia'),
(209, 'Haddaoui', 'Samir', 'samir.haddaoui@school.com', 'Enseignant - Arabe', 'teacherpass', 'teacher', 'gardinia'),
(210, 'Iraqi', 'Hind', 'hind.iraqi@school.com', 'Enseignante - Anglais', 'teacherpass', 'teacher', 'gardinia'),
(211, 'Jabri', 'Younes', 'younes.jabri@school.com', 'Enseignant - Anglais', 'teacherpass', 'teacher', 'gardinia'),
(212, 'Kabbaj', 'Widad', 'widad.kabbaj@school.com', 'Enseignante - Anglais', 'teacherpass', 'teacher', 'gardinia'),
(213, 'Lahlou', 'Anouar', 'anouar.lahlou@school.com', 'Enseignant - Sciences de la Vie et de la Terre', 'teacherpass', 'teacher', 'gardinia'),
(214, 'Mekouar', 'Siham', 'siham.mekouar@school.com', 'Enseignante - Sciences de la Vie et de la Terre', 'teacherpass', 'teacher', 'gardinia'),
(215, 'Naji', 'Othmane', 'othmane.naji@school.com', 'Enseignant - Sciences de la Vie et de la Terre', 'teacherpass', 'teacher', 'gardinia'),
(216, 'Ouahbi', 'Meryem', 'meryem.ouahbi@school.com', 'Enseignante - Physique-Chimie', 'teacherpass', 'teacher', 'gardinia'),
(217, 'Qadiri', 'Hicham', 'hicham.qadiri@school.com', 'Enseignant - Physique-Chimie', 'teacherpass', 'teacher', 'gardinia'),
(218, 'Rifai', 'Sanae', 'sanae.rifai@school.com', 'Enseignante - Physique-Chimie', 'teacherpass', 'teacher', 'gardinia'),
(219, 'Saadi', 'Tarik', 'tarik.saadi@school.com', 'Enseignant - Histoire-Géographie', 'teacherpass', 'teacher', 'gardinia'),
(220, 'Tahiri', 'Ghizlane', 'ghizlane.tahiri@school.com', 'Enseignante - Histoire-Géographie', 'teacherpass', 'teacher', 'gardinia'),
(221, 'Usmani', 'Adnane', 'adnane.usmani@school.com', 'Enseignant - Histoire-Géographie', 'teacherpass', 'teacher', 'gardinia'),
(222, 'Wahbi', 'Rim', 'rim.wahbi@school.com', 'Enseignante - Éducation Islamique', 'teacherpass', 'teacher', 'gardinia'),
(223, 'Yousfi', 'Karima', 'karima.yousfi@school.com', 'Enseignante - Éducation Islamique', 'teacherpass', 'teacher', 'gardinia'),
(224, 'Zniber', 'Fouad', 'fouad.zniber@school.com', 'Enseignant - Éducation Islamique', 'teacherpass', 'teacher', 'gardinia'),
(225, 'Aissaoui', 'Amine', 'amine.aissaoui@school.com', 'Enseignant - Éducation Physique et Sportive', 'teacherpass', 'teacher', 'gardinia'),
(226, 'Belmir', 'Dounia', 'dounia.belmir@school.com', 'Enseignante - Éducation Physique et Sportive', 'teacherpass', 'teacher', 'gardinia'),
(227, 'Chafai', 'Ayoub', 'ayoub.chafai@school.com', 'Enseignant - Éducation Physique et Sportive', 'teacherpass', 'teacher', 'gardinia'),
(228, 'Draoui', 'Hafsa', 'hafsa.draoui@school.com', 'Enseignante - Arts Plastiques', 'teacherpass', 'teacher', 'gardinia'),
(229, 'Essaidi', 'Bilal', 'bilal.essaidi@school.com', 'Enseignant - Arts Plastiques', 'teacherpass', 'teacher', 'gardinia'),
(230, 'Fakhouri', 'Nawal', 'nawal.fakhouri@school.com', 'Enseignante - Arts Plastiques', 'teacherpass', 'teacher', 'gardinia');


-- 100 student accounts (tenant gardinia), matching secretary-office class rosters (userno 301-400).
-- 100 students generated, userno 301-400
INSERT IGNORE INTO tb_user (userno, surname, firstname, email, adresse, password, role, tenant_id) VALUES
(301, 'El Amrani', 'Adam', 'adam.elamrani@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(302, 'Bennani', 'Aya', 'aya.bennani@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(303, 'Alaoui', 'Bilal', 'bilal.alaoui@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(304, 'Idrissi', 'Chaimae', 'chaimae.idrissi@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(305, 'Fassi', 'Dounia', 'dounia.fassi@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(306, 'Naciri', 'Elias', 'elias.naciri@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(307, 'Zahraoui', 'Fatima', 'fatima.zahraoui@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(308, 'Tazi', 'Hamza', 'hamza.tazi@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(309, 'Berrada', 'Imane', 'imane.berrada@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(310, 'Chraibi', 'Jad', 'jad.chraibi@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(311, 'Rami', 'Khadija', 'khadija.rami@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(312, 'Mansouri', 'Lina', 'lina.mansouri@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(313, 'Saidi', 'Mehdi', 'mehdi.saidi@school.com', 'Eleve - classe 1', 'studentpass', 'student', 'gardinia'),
(314, 'Amrani', 'Nada', 'nada.amrani@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(315, 'Bennani', 'Omar', 'omar.bennani@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(316, 'Alaoui', 'Rania', 'rania.alaoui@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(317, 'Idrissi', 'Sami', 'sami.idrissi@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(318, 'Fassi', 'Sara', 'sara.fassi@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(319, 'Naciri', 'Youssef', 'youssef.naciri@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(320, 'Tazi', 'Zineb', 'zineb.tazi@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(321, 'Berrada', 'Anas', 'anas.berrada@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(322, 'Chraibi', 'Basma', 'basma.chraibi@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(323, 'Rami', 'Camil', 'camil.rami@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(324, 'Mansouri', 'Hiba', 'hiba.mansouri@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(325, 'Saidi', 'Ilyas', 'ilyas.saidi@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(326, 'Zahraoui', 'Malak', 'malak.zahraoui@school.com', 'Eleve - classe 2', 'studentpass', 'student', 'gardinia'),
(327, 'El Amrani', 'Amine', 'amine.elamrani@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(328, 'Bennani', 'Asma', 'asma.bennani@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(329, 'Alaoui', 'Ayoub', 'ayoub.alaoui@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(330, 'Idrissi', 'Doha', 'doha.idrissi@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(331, 'Fassi', 'Hajar', 'hajar.fassi@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(332, 'Naciri', 'Ismail', 'ismail.naciri@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(333, 'Tazi', 'Kenza', 'kenza.tazi@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(334, 'Berrada', 'Marouane', 'marouane.berrada@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(335, 'Chraibi', 'Meryem', 'meryem.chraibi@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(336, 'Rami', 'Nabil', 'nabil.rami@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(337, 'Mansouri', 'Nour', 'nour.mansouri@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(338, 'Saidi', 'Rayane', 'rayane.saidi@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(339, 'Zahraoui', 'Salma', 'salma.zahraoui@school.com', 'Eleve - classe 3', 'studentpass', 'student', 'gardinia'),
(340, 'El Amrani', 'Amina', 'amina.elamrani@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(341, 'Bennani', 'Ayoub', 'ayoub.bennani@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(342, 'Alaoui', 'Badr', 'badr.alaoui@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(343, 'Idrissi', 'Dalia', 'dalia.idrissi@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(344, 'Fassi', 'Hassan', 'hassan.fassi@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(345, 'Naciri', 'Ikram', 'ikram.naciri@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(346, 'Tazi', 'Jalal', 'jalal.tazi@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(347, 'Berrada', 'Kawtar', 'kawtar.berrada@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(348, 'Chraibi', 'Maha', 'maha.chraibi@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(349, 'Rami', 'Nassim', 'nassim.rami@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(350, 'Mansouri', 'Oumaima', 'oumaima.mansouri@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(351, 'Saidi', 'Soufiane', 'soufiane.saidi@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(352, 'Zahraoui', 'Wiam', 'wiam.zahraoui@school.com', 'Eleve - classe 4', 'studentpass', 'student', 'gardinia'),
(353, 'El Amrani', 'Ahlam', 'ahlam.elamrani@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(354, 'Bennani', 'Anas', 'anas.bennani@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(355, 'Alaoui', 'Brahim', 'brahim.alaoui@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(356, 'Idrissi', 'Farah', 'farah.idrissi@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(357, 'Fassi', 'Ghita', 'ghita.fassi@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(358, 'Naciri', 'Hamid', 'hamid.naciri@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(359, 'Tazi', 'Ibtissam', 'ibtissam.tazi@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(360, 'Berrada', 'Kamal', 'kamal.berrada@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(361, 'Chraibi', 'Loubna', 'loubna.chraibi@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(362, 'Rami', 'Mouad', 'mouad.rami@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(363, 'Mansouri', 'Najat', 'najat.mansouri@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(364, 'Saidi', 'Othmane', 'othmane.saidi@school.com', 'Eleve - classe 5', 'studentpass', 'student', 'gardinia'),
(365, 'Zahraoui', 'Adil', 'adil.zahraoui@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(366, 'El Amrani', 'Amal', 'amal.elamrani@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(367, 'Bennani', 'Bouchra', 'bouchra.bennani@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(368, 'Alaoui', 'Fouad', 'fouad.alaoui@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(369, 'Idrissi', 'Houda', 'houda.idrissi@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(370, 'Fassi', 'Ibrahim', 'ibrahim.fassi@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(371, 'Naciri', 'Leila', 'leila.naciri@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(372, 'Tazi', 'Mounir', 'mounir.tazi@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(373, 'Berrada', 'Nawal', 'nawal.berrada@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(374, 'Chraibi', 'Reda', 'reda.chraibi@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(375, 'Rami', 'Samira', 'samira.rami@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(376, 'Mansouri', 'Zakaria', 'zakaria.mansouri@school.com', 'Eleve - classe 6', 'studentpass', 'student', 'gardinia'),
(377, 'Saidi', 'Achraf', 'achraf.saidi@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(378, 'Zahraoui', 'Aya', 'aya.zahraoui@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(379, 'El Amrani', 'Chaymae', 'chaymae.elamrani@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(380, 'Bennani', 'Driss', 'driss.bennani@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(381, 'Alaoui', 'Esmae', 'esmae.alaoui@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(382, 'Idrissi', 'Faris', 'faris.idrissi@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(383, 'Fassi', 'Houda', 'houda.fassi@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(384, 'Naciri', 'Soumaya', 'soumaya.naciri@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(385, 'Tazi', 'Jihane', 'jihane.tazi@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(386, 'Berrada', 'Khalil', 'khalil.berrada@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(387, 'Chraibi', 'Meriem', 'meriem.chraibi@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(388, 'Rami', 'Siham', 'siham.rami@school.com', 'Eleve - classe 7', 'studentpass', 'student', 'gardinia'),
(389, 'Mansouri', 'Abir', 'abir.mansouri@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(390, 'Saidi', 'Ayoub', 'ayoub.saidi@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(391, 'Zahraoui', 'Basma', 'basma.zahraoui@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(392, 'El Amrani', 'Hamza', 'hamza.elamrani@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(393, 'Bennani', 'Ines', 'ines.bennani@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(394, 'Alaoui', 'Jad', 'jad.alaoui@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(395, 'Idrissi', 'Khadija', 'khadija.idrissi@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(396, 'Fassi', 'Lamia', 'lamia.fassi@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(397, 'Naciri', 'Meryem', 'meryem.naciri@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(398, 'Tazi', 'Oussama', 'oussama.tazi@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(399, 'Berrada', 'Sara', 'sara.berrada@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia'),
(400, 'Chraibi', 'Yasmine', 'yasmine.chraibi@school.com', 'Eleve - classe 8', 'studentpass', 'student', 'gardinia');

