name: Build & Deploy ecole-portal app

on:
  push:
    branches:
      - main
      - develop
      - test
    paths:
      - 'ecole-portal/**'
      - '.github/workflows/ecole-portal.yml'
      - 'docker-compose.yml'

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push (TEST)
      - name: Build & Push Test Image
        if: github.ref == 'refs/heads/test'
        uses: docker/build-push-action@v5
        with:
          context: ./ecole-portal
          file: ./ecole-portal/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecole-portal:test
          build-args: |
            REACT_APP_API_GATEWAY_URL=${{ secrets.REACT_APP_API_GATEWAY_URL_TEST }}

      # Build & Push (DEVELOP)
      - name: Build & Push Develop Image
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: ./ecole-portal
          file: ./ecole-portal/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecole-portal:develop
          build-args: |
            REACT_APP_API_GATEWAY_URL=${{ secrets.REACT_APP_API_GATEWAY_URL_DEV }}

      # Build & Push (MAIN / PRODUCTION)
      - name: Build & Push Production Image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./ecole-portal
          file: ./ecole-portal/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecole-portal:latest
          build-args: |
            REACT_APP_API_GATEWAY_URL=${{ secrets.REACT_APP_API_GATEWAY_URL_PROD }}

  deploy:
    name: Deploy to Server (main + develop + test)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/test'

    steps:
      - name: Print branch
        run: echo ${{ github.ref_name }}

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            BRANCH="${{ github.ref_name }}"

            if [ "$BRANCH" = "main" ]; then
              IMAGE_TAG=latest
              CONTAINER_NAME=ecole-portal
              PORT=80

            elif [ "$BRANCH" = "test" ]; then
              IMAGE_TAG=test
              CONTAINER_NAME=ecole-portal-test
              PORT=8081

            else
              IMAGE_TAG=develop
              CONTAINER_NAME=ecole-portal-dev
              PORT=8080
            fi

            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecole-portal:$IMAGE_TAG

            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

